In [2]:
import tensorflow as tf
print(tf.__version__)

2.15.0


In [2]:
#Creatw tensors with tf.consant
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# check number of dimensions of a tensor
scalar.ndim

0

In [4]:
#create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
#check num of dimensions of vector
vector.ndim

1

In [6]:
#create matrix(more than 1 deminsion)
matrix = tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [7]:
matrix.ndim

2

In [8]:
another_matrix = tf.constant([[10.,7.],[3., 2.],[8.,9.]],dtype= tf.float16)
#specify data type with dtype^
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [9]:
another_matrix.ndim

2

In [10]:
# Create Tensor!
tensor = tf.constant(
    [[[1,2,3],[4,5,6]],
     [[7,8,9],[10,11,12]],
     [[13,14,15],[16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [11]:
tensor.ndim

3

### **Creating tensors**


In [12]:
changeable = tf.Variable([10,7])
unchangeable = tf.constant([10,7])
changeable,unchangeable

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [13]:
#change elements
changeable[0].assign(7)
changeable

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [14]:
#change elements doesnt work because its a constant
unchangeable[0].assign(7)
unchangeable

AttributeError: ignored

## **Creating Random Tensors**

In [15]:
import tensorflow as tf

# create random but the same tensors
random1 = tf.random.Generator.from_seed(7)
random1 = random1.normal(shape=(3,2))
random2 = tf.random.Generator.from_seed(7)
random2 = random2.normal(shape=(3,2))


random1,random2, random1 == random2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### **Shuffling tensors**

In [16]:
notShuffled = tf.constant([[10,7]
                           ,[3,4]
                           ,[2,5]])
tf.random.shuffle(notShuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

In [17]:
tf.random.set_seed(42)
tf.random.shuffle(notShuffled, seed=28)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

## **Creating specific tensors**

In [18]:
#creates a tensor of all ones
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [19]:
#creates a tensor of all zeros
tf.zeros([3,4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### Turn NumPy arrays into tensors

In [20]:
import numpy as np
numpyArray = np.arange(1,25, dtype=np.int32) #creates array between 1 and 25
numpyArray

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A = tf.constant(numpyArray, shape=(3,8))
B = tf.constant(numpyArray, shape=(6,2,2))
A,B


## **Getting Information from tensors**


*   shape
*   rank
* axis or dimension
* size



In [22]:
#create rank 4 tensor
rank4Tensor = tf.zeros(shape=[2,3,4,5])
rank4Tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [23]:
#get various attributes of tensor
print("Datatype of every element", rank4Tensor.dtype)
print("Number of dimensions (rank):", rank4Tensor.ndim)
print("Shape of tensor:", rank4Tensor.shape)
print("Elements along the 0 axis:", rank4Tensor.shape[0])
print("Elements along the last axis:", rank4Tensor.shape[-1])
print("Total number of elements in our tensor:", tf.size(rank4Tensor).numpy())

Datatype of every element <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along the 0 axis: 2
Elements along the last axis: 5
Total number of elements in our tensor: 120


# **Indexing tensors**

In [24]:
rank4Tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [29]:
rank2Tensor= tf.constant([[10,7]
                           ,[3,4]])

#get last item of each row
rank2Tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [32]:
#Add an extra dimension
rank3Tensor = rank2Tensor[:,:,tf.newaxis]
rank3Tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [37]:
#Alternative to tf.newaxis
tf.expand_dims(rank2Tensor,-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

## **Manipulating Tensors**

In [38]:
#tensor operations
tensor= tf.constant([[10,7],[3,4]])
tensor +10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [40]:
tf.add(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [39]:
tensor*10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [41]:
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

Matrix multiplication

In [42]:
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [43]:
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

**Matrix multiplication rules**


1.   inner demensions must match
2.   the resulting matrix has the same shape of the inner deminsions



In [46]:
#multiplying 2 same size tensors wont work
x = tf.constant([[1,2],
                 [3,4],
                 [5,6]])
y = tf.constant([[7,8],
                 [9,10],
                 [11,12]])
x @ y

InvalidArgumentError: ignored

In [55]:
#reshape tensor
y, tf.reshape(y, (2,3))


(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 7,  8,  9],
        [10, 11, 12]], dtype=int32)>)

In [58]:
# inner demensions are now the same (2) so it will work
x.shape, tf.reshape(y,(2,3)).shape, x @ tf.reshape(y,(2,3))
# result will be same shape as outer deminsions 3x3

(TensorShape([3, 2]),
 TensorShape([2, 3]),
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]], dtype=int32)>)

In [59]:
#Transpose will flip demensions and can be used instead of reshape
tf.transpose(y)
#note numbers are not the same as in reshape

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  9, 11],
       [ 8, 10, 12]], dtype=int32)>

In [60]:
x @ tf.transpose(y)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

**One Hot Encoding tensors**

In [3]:
sList =[0,1,2,3]
tf.one_hot(sList, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [4]:
sList =[0,1,2,2]
tf.one_hot(sList, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.]], dtype=float32)>

In [6]:
sList =[0,1,2,3]
tf.one_hot(sList, depth=4,on_value="a", off_value="z")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'a', b'z', b'z', b'z'],
       [b'z', b'a', b'z', b'z'],
       [b'z', b'z', b'a', b'z'],
       [b'z', b'z', b'z', b'a']], dtype=object)>

## cast tensor to new dtypes

In [9]:
tensor= tf.constant([[10,7],[3,4]])
tensor,tf.cast(tensor, dtype=tf.float16)


(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=float16, numpy=
 array([[10.,  7.],
        [ 3.,  4.]], dtype=float16)>)